import { Routes } from '@angular/router';
import { HomeComponent } from './pages/home/home.component';
import { ExperienceComponent } from './pages/experience/experience.component';
import { ProjectsComponent } from './pages/projects/projects.component';
import { ProjectDetailComponent } from './pages/projects/project-detail.component';
import { SkillsComponent } from './pages/skills/skills.component';
import { DSAComponent } from './pages/dsa.component';
import { DiagramComponent } from './pages/diagram/diagram.component';
import { NotesComponent } from './pages/notes/notes.component';
import { PythonDetailsComponent } from './pages/notes/python/python-details.component';
import { PrintConsoleNotesComponent } from './pages/notes/python/print-console/notes.component';
import { VariablesDataTypesNotesComponent } from './pages/notes/python/variables-data-types/notes.component';
import { OperatorsNotesComponent } from './pages/notes/python/operators/notes.component';
import { TypeConversionNotesComponent } from './pages/notes/python/type-conversion/notes.component';
import { NotFoundComponent } from './common/not-found.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'experience', component: ExperienceComponent },
  { path: 'skills', component: SkillsComponent },
  { path: 'projects', component: ProjectsComponent },
  { path: 'dsa', component: DSAComponent },
  { path: 'diagram', component: DiagramComponent },
  { path: 'notes', component: NotesComponent },
  { path: 'notes/python', component: PythonDetailsComponent },
  { path: 'notes/python/print-console', component: PrintConsoleNotesComponent },
  { path: 'notes/python/variables-data-types', component: VariablesDataTypesNotesComponent },
  { path: 'notes/python/operators', component: OperatorsNotesComponent },
  { path: 'notes/python/type-conversion', component: TypeConversionNotesComponent },
  { path: 'project/:id', component: ProjectDetailComponent },
  { path: '**', component: NotFoundComponent }
];